### ISSUE TITLE
Kronos not working in production

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#451]
Since 30Apr, we looks like stuck on terms of message consumption. 
Looking at the pod logs I see a lot of these errros (*). @ericvaandering @yuyiguo can you check on this? The queue is growing pretty badly.

Exception in thread Thread-74:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/stomp/transport.py", line 346, in __receiver_loop
    self.process_frame(f, frame)
  File "/usr/local/lib/python3.6/site-packages/stomp/transport.py", line 193, in process_frame
    self.notify(frame_type, f)
  File "/usr/local/lib/python3.6/site-packages/stomp/transport.py", line 246, in notify
    notify_func(frame)
  File "/usr/local/lib/python3.6/site-packages/rucio/core/monitor.py", line 405, in _wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rucio/daemons/tracer/kronos.py", line 116, in on_message
    self.__conn.ack(msg_id, self.__subscription_id)
  File "/usr/local/lib/python3.6/site-packages/stomp/protocol.py", line 277, in ack
    self.send_frame(CMD_ACK, headers)
  File "/usr/local/lib/python3.6/site-packages/stomp/protocol.py", line 246, in send_frame
    self.transport.transmit(frame)
  File "/usr/local/lib/python3.6/site-packages/stomp/transport.py", line 273, in transmit
    self.send(packed_frame)
  File "/usr/local/lib/python3.6/site-packages/stomp/transport.py", line 652, in send
    raise exception.NotConnectedException()
stomp.exception.NotConnectedException

**Comment by dciangot** [comment]
if of any help, this behavior started on 29 March, that is exactly when we got a big spike in transfer requests triggered by ops.

**Comment by ericvaandering** [comment]
A complete refusal to connect is new to me and it looks like that is what is happening.
