### ISSUE TITLE
[BUG] Rucio Consistency Check Page not available

### ISSUE THREAD

**Issue by guyzsarun** [dmwm/CMSRucio#622]
**Describe the bug**
Since yesterday/ today CE page is not available  [1], could be related to https://github.com/dmwm/rucio-flux/pull/208
Could you please take a look at it?
Thanks,
Guy

[1]
https://cmsweb.cern.ch/rucioconmon/ce/index

Logs
```
Application error
'<' not supported between instances of 'NoneType' and 'float'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/webpie/WPApp.py", line 644, in wsgi_call
    response = root_handler._handle_request(request, "", path_down, args)
  File "/usr/local/lib/python3.10/site-packages/webpie/WPApp.py", line 437, in _handle_request
    return subhandler._handle_request(request, path + "/" + word, path_down, args)
  File "/usr/local/lib/python3.10/site-packages/webpie/WPApp.py", line 435, in _handle_request
    return subhandler(request, relpath, **args)
  File "/root/app/ce_handler.py", line 100, in index
    if summary["order"] is None and summary["start_time"] < now - 14*24*3600:          # older than 2 weeks
TypeError: '<' not supported between instances of 'NoneType' and 'float'
```

**Comment by ivmfnal** [comment]
Fixed that

**Comment by guyzsarun** [comment]
Thanks @ivmfnal !
