### ISSUE TITLE
Issues with new python client installation

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#626]
**Describe the bug**

As of Oct 5, jobs using the rucio setup scripts from cvmfs started to failed with the following traceback. 
```
tunikode@lxplus806 ~ $ k exec -n hdfs -it cron-size-quotas-66d6c6f5b5-mslt2 -- /bin/bash
[root@cron-size-quotas-66d6c6f5b5-mslt2 data]# python3
Python 3.9.12 (main, Aug  9 2023, 10:29:12) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> exit()
[root@cron-size-quotas-66d6c6f5b5-mslt2 data]# . /cvmfs/cms.cern.ch/rucio/setup-py3.sh
rucio 1.31.7
[root@cron-size-quotas-66d6c6f5b5-mslt2 data]# python3
Python 3.9.12 (main, Aug  9 2023, 10:29:12) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.9/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/usr/local/lib/python3.9/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/usr/local/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 67, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 142, in <module>
    from pandas.core.generic import (
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 178, in <module>
    from pandas.core.methods.describe import describe_ndframe
  File "/usr/local/lib/python3.9/site-packages/pandas/core/methods/describe.py", line 41, in <module>
    from pandas.io.formats.format import format_percentiles
  File "/usr/local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 91, in <module>
    from pandas.io.common import (
  File "/usr/local/lib/python3.9/site-packages/pandas/io/common.py", line 88, in <module>
    class IOArgs:
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 800, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 800, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'
```

**To Reproduce**

1. Setup rucio using the cvmfs script: `source /cvmfs/cms.cern.ch/rucio/setup-py3.sh`
2.   With python version > 3.6; start REPL
3. import pandas 

**Expected behavior**
Should run without any error.

**Additional context**

The new installation has the `dataclass.py` file in the PYTHONPATH, backported possibly for python 3.6
But it causes problems in newer versions of Python which have the dataclass module built in. 
https://docs.python.org/3/library/dataclasses.html

**Comment by ericvaandering** [comment]
Better discussed in [cms-sw/cmsdist#8739](https://github.com/cms-sw/cmsdist/issues/8739)
